{% set name = "pyoints" %}
{% set data = load_setup_py_data() %}


package:
    name: {{ name }}
    version: {{ data.get('version') }}
  
source:
    #git_url: "https://github.com/laempy/pyoints"
    git_url: "../.git"
  
build:
    number: 0
    #script: "{{ PYTHON }} -m pip install . --ignore-installed -vvv"
    #missing_dso_whitelist:
    #    - /lib64/libutil.so.1 
    #    - /lib64/libpthread.so.0
    #    - /lib64/libc.so.6
    #    - /lib64/libdl.so.2
    #    - /lib64/librt.so.1
    
requirements:
    build:
        - python {{ python }}
        - pip
        - gdal
        - conda-verify
    dependencies:
        - python
        - gdal
        - pip
            - cylinder_fitting
            - opencv-python
            - matplotlib
            - plyfile
            - laspy
    run:
        - python
        - gdal
        - dill
        - networkx
        - numpy
        - pandas
        - rtree
        - scikit-learn
        - scipy
        - pyproj

test:
    imports:
        - cv2
        - osgeo
        - plyfile
        - cylinder_fitting
        - laspy
        - pyoints
        - pyoints.examples
        - pyoints.examples.file_examples
        - pyoints.grid
        - pyoints.registration
        - pyoints.storage
    requirements:
        - unittest
        - doctest
        - pkgutil
        - python {{ python }}
    source_files:
        - tests/test_pyoints.py
    commands:
        - python -c "from tests.test_pyoints import runall; runall();"
        
about:
    home: https://laempy.github.io/pyoints/modules.html
    license: GNU General Public v3 or later (GPLv3+)
    license_family: GPL3
    license_file: ../LICENSE
    summary: A Python package for point cloud, voxel and raster processing.
    doc_url: https://laempy.github.io/pyoints/pyoints.html
    dev_url: https://github.com/laempy/pyoints

extra:
    recipe-maintainers:
        - laempy