{% set name = "pyoints" %}
{% set data = load_setup_py_data() %}


package:
    name: {{ name }}
    version: {{ data.get('version') }}
  

source:
    #git_url: "https://github.com/laempy/pyoints"
    git_url: "../.git"
  

build:
    number: 0
    #ignore_prefix_files: True  # required for windows binary files
    #detect_binary_files_with_prefix: False
    #script: "{{ PYTHON }} -m pip install . --ignore-installed -vvv"

requirements:
    build:
        - python #{{ python }}
        - pip
        - setuptools
        #- vc# 14  # [win]
        #- pyproj
        #- {{ compiler('c') }}
        #- {{ compiler('c') }}
    host:
        - python {{ python }}
        #- vc
        #- {{ compiler('c') }}
        #- pip
        #- setuptools
        #- {{ compiler('c') }}
    #dependencies:
    #    - python {{ python }}
        #- pip
        #    - cylinder_fitting
            #- opencv-python
        #    - plyfile
        #    - laspy
    run:
        - python {{ python }}
        - gdal
        - pyproj  # pyproj from pip fails for windows
        - rtree  # rtree from pip fails for windows
        #- libspatialindex  # throws error
        #- gdal
        #- rtree
        #- python {{ python }}
        #- gdal
        #- dill
        #- opencv
        #- networkx
        #- numpy>=1.15
        #- pandas
        #- rtree
        #- scikit-learn
        #- scipy
        #- pyproj
        #- laspy
        #- plyfile
        


#test:  # [linux]
test:
    imports:
        - osgeo
        - cv2
        - laspy
        - plyfile
        - cylinder_fitting
        - pyproj
        - rtree
        - pyoints
        - pyoints.examples
        - pyoints.examples.file_examples
        - pyoints.grid
        - pyoints.registration
        - pyoints.storage
    requirements:
    #    #- python {{ python }}
        - unittest
        - doctest
        - pkgutil
    source_files:
        - tests/test_pyoints.py
        
about:
    home: https://laempy.github.io/pyoints/modules.html
    license: GNU General Public v3 or later (GPLv3+)
    license_family: GPL3
    license_file: ../LICENSE
    summary: A Python package for point cloud, voxel and raster processing.
    doc_url: https://laempy.github.io/pyoints/pyoints.html
    dev_url: https://github.com/laempy/pyoints

extra:
    recipe-maintainers:
        - laempy