{% set name = "pyoints" %}
{% set data = load_setup_py_data() %}


package:
    name: {{ name }}
    version: {{ data.get('version') }}
  

source:
    #git_url: "https://github.com/laempy/pyoints"
    git_url: "../.git"
  

build:
    number: 0
    #ignore_prefix_files: True  # required for windows binary files
    #detect_binary_files_with_prefix: False
    #script: "{{ PYTHON }} -m pip install . --ignore-installed -vvv"

    
requirements:
    build:
        - python #{{ python }}
        - pip
        - setuptools
        #- {{ compiler('c') }}
    host:
        - python {{ python }}
        #- pip
        #- setuptools
        #- {{ compiler('c') }}
    #dependencies:
    #    - python {{ python }}
        #- gdal
        #- libspatialindex
        #- pip
        #    - cylinder_fitting
            #- opencv-python
        #    - plyfile
        #    - laspy
    run:
        - python {{ python }}
        - gdal
        - libspatialindex
        #- libspatialindex  # throws error
        #- gdal
        #- rtree
        #- python {{ python }}
        #- gdal
        #- dill
        #- opencv
        #- networkx
        #- numpy>=1.15
        #- pandas
        #- rtree
        #- scikit-learn
        #- scipy
        #- pyproj
        #- laspy
        #- plyfile
        


test:  # [linux]
    imports:
        - osgeo
        - cv2
        - laspy
        - plyfile
        - cylinder_fitting
        - pyoints
        - pyoints.examples
        - pyoints.examples.file_examples
        - pyoints.grid
        - pyoints.registration
        - pyoints.storage
    #requirements:
    #    #- python {{ python }}
    #    - unittest
    #    - doctest
    #    - pkgutil
    source_files:
        - tests/test_pyoints.py
    #commands:
        #- python -c "from tests.test_pyoints import runall; runall();"
        #- $PYTHON -c "from tests.test_pyoints import runall; runall();"
        
about:
    home: https://laempy.github.io/pyoints/modules.html
    license: GNU General Public v3 or later (GPLv3+)
    license_family: GPL3
    license_file: ../LICENSE
    summary: A Python package for point cloud, voxel and raster processing.
    doc_url: https://laempy.github.io/pyoints/pyoints.html
    dev_url: https://github.com/laempy/pyoints

extra:
    recipe-maintainers:
        - laempy
    #channels:
    #    - conda-forge
    #    - kitware-geospatial
    #    - kayarre
  
  
#pygdal
#numpy>=1.15
#rtree
#laspy
#scipy
#scikit-learn
#pyproj
#dill
#pandas
#opencv-python
#plyfile
#networkx
#cylinder_fitting