{% set name = "pyoints" %}
{% set data = load_setup_py_data() %}


package:
    name: {{ name }}
    version: {{ data.get('version') }}

source:
    git_url: "../.git"

build:
    #number: 0
    skip: True  # [not py3k]

requirements:
    host:
        - python {{ python }}
        - pip
        - gdal  # pygdal is not able to detect gdal version
        - numpy>=1.15
    run:
        - python {{ python }}
        - {{ pin_compatible('gdal') }}
        - {{ pin_compatible('numpy') }}
        - pyproj  # pyproj via pip fails for Windows
        - rtree  # rtree via pip fails for Windows

test:
    imports:
        - numpy
        - osgeo
        - cv2
        - laspy
        - plyfile
        - pyproj
        - rtree
        - cylinder_fitting
        - pyoints
        - pyoints.examples
        - pyoints.grid
        - pyoints.registration
        - pyoints.storage

about:
    home: https://laempy.github.io/pyoints/modules.html
    license: GNU General Public v3 or later (GPLv3+)
    license_family: GPL3
    license_file: ../LICENSE
    summary: A Python package for point cloud, voxel and raster processing.
    doc_url: https://laempy.github.io/pyoints/pyoints.html
    dev_url: https://github.com/laempy/pyoints

extra:
    recipe-maintainers:
        - laempy